[package]
name = "wasi2ic"
version = "0.2.12"
edition = "2021"
description = "This tool converts WebAssembly System Interface (WASI) dependent Wasm files to be compatible with the Internet Computer (IC) platform."
keywords = ["ic", "internet-computer", "wasi"]
license = "MIT"
repository = "https://github.com/wasm-forge/wasi2ic"


[dependencies]
walrus = "0.20.3"
clap = { version = "4.5.9", features = ["derive"] }
anyhow = { version = "1.0", default-features = false }
env_logger = "0.11.0"
log = "0.4.17"
wasmprinter = "0.212.0"
wat = "1.212.0"
